fix(package): upgrade dependencies
indec-it/seed-react-native pull request #1
Opened 2019-01-08 15:52 UTC by maximilianoforlenza

fix(package): upgrade dependencies

2019-01-10 03:01 UTC, navarroaxel requested changes

2019-01-10 03:01 UTC, navarroaxel commented on android/app/BUCK
> +    package = "ar.gob.indec.rfb",
`ar.gob.indec.seed`

2019-01-10 03:01 UTC, navarroaxel commented on android/app/BUCK
> +    package = "ar.gob.indec.rfb",
`ar.gob.indec.seed`

2019-01-10 03:01 UTC, navarroaxel commented on android/app/build.gradle
> +        applicationId "ar.gob.indec.rfb"
`ar.gob.indec.seed`

2019-01-10 03:01 UTC, navarroaxel commented on android/app/src/main/AndroidManifest.xml
> +    package="ar.gob.indec.rfb">
`ar.gob.indec.seed`

2019-01-10 03:01 UTC, navarroaxel commented on android/app/src/main/java/ar/gob/indec/rfb/MainActivity.java
> +package ar.gob.indec.rfb;
`ar.gob.indec.seed`

2019-01-10 13:37 UTC, maximilianoforlenza commented
listo

2019-01-12 21:52 UTC, maximilianoforlenza commented
listo, agregue `react-native-fontawesome` tambien

2019-01-12 22:30 UTC, navarroaxel commented
Pero habría que sacar `react-native-vector-icons` ya que no se usaría más.

2019-01-12 22:32 UTC, maximilianoforlenza commented
`react-native-elements` lo necesita

2019-01-15 14:48 UTC, maximilianoforlenza commented
listo

2019-01-22 17:50 UTC, navarroaxel approved these changes

2019-01-22 17:50 UTC, navarroaxel commented on package.json
> +    "react-test-renderer": "^16.7.0",
si no se usa remover.

2019-01-22 17:50 UTC, navarroaxel commented on package.json
> +    "babel-jest": "^23.6.0",
si no se usa remover.

2019-01-22 17:50 UTC, navarroaxel commented on package.json
>      "babel-core": "^6.26.0",
usar el `babel-core@bridge`

2019-01-22 17:50 UTC, navarroaxel commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.6.3",
remover y usamos el `react-native-vector-icons`.

2019-01-22 17:52 UTC, merged